apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-utkast
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 15
  prometheus:
    path: /metrics
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 100
  leaderElection: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
        - application: tms-min-side-proxy
        - application: tms-utkast-frontend
        - application: sosialhjelp-soknad-api
          namespace: teamdigisos
    outbound:
      rules:
        - application: innsending
          namespace: aap
          cluster: prod-gcp
        - application: sosialhjelp-soknad-api
          namespace: teamdigisos
        - application: logging
          namespace: nais-system
      external:
        - host: sosialhjelp-soknad-api.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
      - name: utkast
        type: POSTGRES_14
        tier: db-custom-1-4096
        diskType: SSD
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: utkast
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: "20m"
      memory: 256Mi
  env:
    - name: GROUP_ID
      value: tms-utkast-01
    - name: KAFKA_TOPIC
      value: min-side.aapen-utkast-v1
    - name: DIGISOS_BASE_URL
      value: http://sosialhjelp-soknad-api.teamdigisos/sosialhjelp/soknad-api
    - name: DIGISOS_CLIENT_ID
      value: prod-gcp:teamdigisos:sosialhjelp-soknad-api
    - name: AAP_CLIENT_ID
      value: prod-gcp:aap:innsending
