name: Bygg og publiser bibliotek
push:
  branches:
    - main
  paths:
    - '.lib/src/main/**'

jobs:
  run-test:
    -
    - name: Sjekk ut koden
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '17.x'

    - name: Bygg bibliotek
      run:  ./gradlew build

    - name: Tagg release
      run: |
        TAG="$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(git log -1 --pretty='%h')" 
        git tag $TAG
        git push origin $TAG
